# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cloth App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Cloth App
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'SwiftyJSON'
  pod 'Firebase'
  pod 'FirebaseMessaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics', '~> 10.5'
  pod 'FacebookLogin'
  pod 'FBSDKShareKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'KRProgressHUD'
  pod 'Kingfisher'
  pod 'moa'
  pod 'Auk'
  pod 'CarbonKit'
  pod 'TagListView', '~> 1.0'
  pod 'TTRangeSlider'
  pod 'GrowingTextView'
  pod 'StripePaymentSheet', '~> 25.0.0'
  pod 'AlignedCollectionViewFlowLayout'
  #  pod 'GoogleMaps'#, :modular_headers => true
  #  pod 'GooglePlaces'#, :modular_headers => true
  # ⚠️ Optional: Remove if causing device-only issue
  pod 'GoogleMaps', '3.1.0'
  pod 'GooglePlaces', '3.1.0'
  
  pod 'CHIPageControl', '~> 0.1.3'
  pod 'MercariQRScanner'
  pod 'Google-Mobile-Ads-SDK'
  pod 'IBAnimatable'
  pod 'OTPFieldView'
  pod 'YPImagePicker'
  pod 'Cosmos'
  pod 'libPhoneNumber-iOS'
  pod 'SDWebImage'
  pod 'TOCropViewController', '~> 2.7.0'
end
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
