-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTKh7i0f3Mr0blPHc
ZrSCHvKniJTs8UpH1pPL8Bh5DCegCgYIKoZIzj0DAQehRANCAARDswNKeDlnPwI3
k5ZZfdXWejtxYWrgTwNCJ10Q6MnUX8PgLAaP7TXOLnfZ2J9mCQgE2ufGNaRues/Q
v0yEzJ4A
-----END PRIVATE KEY-----